/* 
 * EVE Swagger Interface
 *
 * An OpenAPI for EVE Online
 *
 * OpenAPI spec version: 0.4.1.dev1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

package swagger

// item object
type GetCharactersCharacterIdBookmarksItem struct {

	// item_id integer
	ItemId int64 `json:"item_id,omitempty"`

	// type_id integer
	TypeId int32 `json:"type_id,omitempty"`
}
