/* 
 * EVE Swagger Interface
 *
 * An OpenAPI for EVE Online
 *
 * OpenAPI spec version: 0.4.1.dev1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

package swagger

// 200 ok object
type GetCharactersCharacterIdMailLabelsOk struct {

	// labels array
	Labels []GetCharactersCharacterIdMailLabelsLabel `json:"labels,omitempty"`

	// total_unread_count integer
	TotalUnreadCount int32 `json:"total_unread_count,omitempty"`
}
