/* 
 * EVE Swagger Interface
 *
 * An OpenAPI for EVE Online
 *
 * OpenAPI spec version: 0.4.1.dev1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

package swagger

// 200 ok object
type GetCharactersCharacterIdMailLists200Ok struct {

	// Mailing list ID
	MailingListId int32 `json:"mailing_list_id,omitempty"`

	// name string
	Name string `json:"name,omitempty"`
}
