/* 
 * EVE Swagger Interface
 *
 * An OpenAPI for EVE Online
 *
 * OpenAPI spec version: 0.4.1.dev1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

package swagger

// jump_clone object
type GetCharactersCharacterIdClonesJumpClone struct {

	// implants array
	Implants []int32 `json:"implants,omitempty"`

	// location_id integer
	LocationId int64 `json:"location_id,omitempty"`

	// location_type string
	LocationType string `json:"location_type,omitempty"`
}
