/* 
 * EVE Swagger Interface
 *
 * An OpenAPI for EVE Online
 *
 * OpenAPI spec version: 0.4.1.dev1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

package swagger

import (
	"time"
)

// 200 ok object
type GetAlliancesAllianceIdOk struct {

	// the full name of the alliance
	AllianceName string `json:"alliance_name,omitempty"`

	// date_founded string
	DateFounded time.Time `json:"date_founded,omitempty"`

	// the executor corporation ID, if this alliance is not closed
	ExecutorCorp int32 `json:"executor_corp,omitempty"`

	// the short name of the alliance
	Ticker string `json:"ticker,omitempty"`
}
