/* 
 * EVE Swagger Interface
 *
 * An OpenAPI for EVE Online
 *
 * OpenAPI spec version: 0.4.1.dev1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

package swagger

// 200 ok object
type GetAlliancesAllianceIdIconsOk struct {

	// px128x128 string
	Px128x128 string `json:"px128x128,omitempty"`

	// px64x64 string
	Px64x64 string `json:"px64x64,omitempty"`
}
