/* 
 * EVE Swagger Interface
 *
 * An OpenAPI for EVE Online
 *
 * OpenAPI spec version: 0.4.1.dev1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

package swagger

// 200 ok object
type GetLoyaltyStoresCorporationIdOffers200Ok struct {

	// isk_cost number
	IskCost float32 `json:"isk_cost,omitempty"`

	// lp_cost integer
	LpCost int32 `json:"lp_cost,omitempty"`

	// offer_id integer
	OfferId int32 `json:"offer_id,omitempty"`

	// quantity integer
	Quantity int32 `json:"quantity,omitempty"`

	// required_items array
	RequiredItems []GetLoyaltyStoresCorporationIdOffersRequiredItem `json:"required_items,omitempty"`

	// type_id integer
	TypeId int32 `json:"type_id,omitempty"`
}
