/* 
 * EVE Swagger Interface
 *
 * An OpenAPI for EVE Online
 *
 * OpenAPI spec version: 0.4.1.dev1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

package swagger

// 200 ok object
type GetUniversePlanetsPlanetIdOk struct {

	// name string
	Name string `json:"name,omitempty"`

	// planet_id integer
	PlanetId int32 `json:"planet_id,omitempty"`

	Position GetUniversePlanetsPlanetIdPosition `json:"position,omitempty"`

	// The solar system this planet is in
	SystemId int32 `json:"system_id,omitempty"`

	// type_id integer
	TypeId int32 `json:"type_id,omitempty"`
}
