/* 
 * EVE Swagger Interface
 *
 * An OpenAPI for EVE Online
 *
 * OpenAPI spec version: 0.4.1.dev1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

package swagger

// coordinates object
type GetCharactersCharacterIdBookmarksCoordinates struct {

	// x number
	X float64 `json:"x,omitempty"`

	// y number
	Y float64 `json:"y,omitempty"`

	// z number
	Z float64 `json:"z,omitempty"`
}
