/* 
 * EVE Swagger Interface
 *
 * An OpenAPI for EVE Online
 *
 * OpenAPI spec version: 0.4.1.dev1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

package swagger

// cost_indice object
type GetIndustrySystemsCostIndice struct {

	// activity string
	Activity string `json:"activity,omitempty"`

	// cost_index number
	CostIndex float32 `json:"cost_index,omitempty"`
}
