/* 
 * EVE Swagger Interface
 *
 * An OpenAPI for EVE Online
 *
 * OpenAPI spec version: 0.4.1.dev1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

package swagger

// waypoint object
type GetCharactersCharacterIdPlanetsPlanetIdWaypoint struct {

	// order integer
	Order int32 `json:"order,omitempty"`

	// pin_id integer
	PinId int64 `json:"pin_id,omitempty"`
}
