/* 
 * EVE Swagger Interface
 *
 * An OpenAPI for EVE Online
 *
 * OpenAPI spec version: 0.4.1.dev1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

package swagger

// ally object
type GetWarsWarIdAlly struct {

	// Alliance ID if and only if this ally is an alliance
	AllianceId int32 `json:"alliance_id,omitempty"`

	// Corporation ID if and only if this ally is a corporation
	CorporationId int32 `json:"corporation_id,omitempty"`
}
