/* 
 * EVE Swagger Interface
 *
 * An OpenAPI for EVE Online
 *
 * OpenAPI spec version: 0.4.1.dev1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

package swagger

// target object
type GetCharactersCharacterIdBookmarksTarget struct {

	Coordinates GetCharactersCharacterIdBookmarksCoordinates `json:"coordinates,omitempty"`

	Item GetCharactersCharacterIdBookmarksItem `json:"item,omitempty"`

	// location_id integer
	LocationId int64 `json:"location_id,omitempty"`
}
