/* 
 * EVE Swagger Interface
 *
 * An OpenAPI for EVE Online
 *
 * OpenAPI spec version: 0.4.1.dev1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

package swagger

// 200 ok object
type GetUniverseStargatesStargateIdOk struct {

	Destination GetUniverseStargatesStargateIdDestination `json:"destination,omitempty"`

	// name string
	Name string `json:"name,omitempty"`

	Position GetUniverseStargatesStargateIdPosition `json:"position,omitempty"`

	// stargate_id integer
	StargateId int32 `json:"stargate_id,omitempty"`

	// The solar system this stargate is in
	SystemId int32 `json:"system_id,omitempty"`

	// type_id integer
	TypeId int32 `json:"type_id,omitempty"`
}
