/* 
 * EVE Swagger Interface
 *
 * An OpenAPI for EVE Online
 *
 * OpenAPI spec version: 0.4.1.dev1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

package swagger

import (
	"time"
)

// 200 ok object
type GetCharactersCharacterIdClonesOk struct {

	HomeLocation GetCharactersCharacterIdClonesHomeLocation `json:"home_location,omitempty"`

	// jump_clones array
	JumpClones []GetCharactersCharacterIdClonesJumpClone `json:"jump_clones,omitempty"`

	// last_jump_date string
	LastJumpDate time.Time `json:"last_jump_date,omitempty"`
}
