/* 
 * EVE Swagger Interface
 *
 * An OpenAPI for EVE Online
 *
 * OpenAPI spec version: 0.4.1.dev1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

package swagger

// 200 ok object
type GetCharactersNames200Ok struct {

	// character_id integer
	CharacterId int64 `json:"character_id,omitempty"`

	// character_name string
	CharacterName string `json:"character_name,omitempty"`
}
