/* 
 * EVE Swagger Interface
 *
 * An OpenAPI for EVE Online
 *
 * OpenAPI spec version: 0.4.1.dev1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

package swagger

import (
	"time"
)

// 200 ok object
type GetCharactersCharacterIdMailMailIdOk struct {

	// Mail's body
	Body string `json:"body,omitempty"`

	// From whom the mail was sent
	From int32 `json:"from,omitempty"`

	// Labels attached to the mail
	Labels []int64 `json:"labels,omitempty"`

	// Whether the mail is flagged as read
	Read bool `json:"read,omitempty"`

	// Recipients of the mail
	Recipients []GetCharactersCharacterIdMailMailIdRecipient `json:"recipients,omitempty"`

	// Mail subject
	Subject string `json:"subject,omitempty"`

	// When the mail was sent
	Timestamp time.Time `json:"timestamp,omitempty"`
}
