/* 
 * EVE Swagger Interface
 *
 * An OpenAPI for EVE Online
 *
 * OpenAPI spec version: 0.4.1.dev1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

package swagger

// 200 ok object
type GetCharactersCharacterIdWallets200Ok struct {

	// Wallet's balance in ISK hundredths.
	Balance int64 `json:"balance,omitempty"`

	// wallet_id integer
	WalletId int32 `json:"wallet_id,omitempty"`
}
