/* 
 * EVE Swagger Interface
 *
 * An OpenAPI for EVE Online
 *
 * OpenAPI spec version: 0.4.1.dev1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

package swagger

// 200 ok object
type GetCharactersCharacterIdBookmarksFolders200Ok struct {

	// folder_id integer
	FolderId int32 `json:"folder_id,omitempty"`

	// name string
	Name string `json:"name,omitempty"`

	// owner_id integer
	OwnerId int32 `json:"owner_id,omitempty"`
}
