/* 
 * EVE Swagger Interface
 *
 * An OpenAPI for EVE Online
 *
 * OpenAPI spec version: 0.4.1.dev1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

package swagger

// factory_details object
type GetCharactersCharacterIdPlanetsPlanetIdFactoryDetails struct {

	// schematic_id integer
	SchematicId int32 `json:"schematic_id,omitempty"`
}
