/* 
 * EVE Swagger Interface
 *
 * An OpenAPI for EVE Online
 *
 * OpenAPI spec version: 0.4.1.dev1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

package swagger

// 200 ok object
type GetUniverseRegionsRegionIdOk struct {

	// constellations array
	Constellations []int32 `json:"constellations,omitempty"`

	// description string
	Description string `json:"description,omitempty"`

	// name string
	Name string `json:"name,omitempty"`

	// region_id integer
	RegionId int32 `json:"region_id,omitempty"`
}
