/* 
 * EVE Swagger Interface
 *
 * An OpenAPI for EVE Online
 *
 * OpenAPI spec version: 0.4.1.dev1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

package swagger

// 200 ok object
type GetWarsWarIdKillmails200Ok struct {

	// A hash of this killmail
	KillmailHash string `json:"killmail_hash,omitempty"`

	// ID of this killmail
	KillmailId int32 `json:"killmail_id,omitempty"`
}
