/* 
 * EVE Swagger Interface
 *
 * An OpenAPI for EVE Online
 *
 * OpenAPI spec version: 0.4.1.dev1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

package swagger

// 200 ok object
type GetCharactersCharacterIdContactsLabels200Ok struct {

	// label_id integer
	LabelId int64 `json:"label_id,omitempty"`

	// label_name string
	LabelName string `json:"label_name,omitempty"`
}
