/* 
 * EVE Swagger Interface
 *
 * An OpenAPI for EVE Online
 *
 * OpenAPI spec version: 0.4.1.dev1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

package swagger

// 200 ok object
type GetAlliancesNames200Ok struct {

	// alliance_id integer
	AllianceId int32 `json:"alliance_id,omitempty"`

	// alliance_name string
	AllianceName string `json:"alliance_name,omitempty"`
}
