/* 
 * EVE Swagger Interface
 *
 * An OpenAPI for EVE Online
 *
 * OpenAPI spec version: 0.4.1.dev1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

package swagger

// No image server for this datasource
type GetCharactersCharacterIdPortraitNotFound struct {

	// error message
	Error_ string `json:"error,omitempty"`
}
