/* 
 * EVE Swagger Interface
 *
 * An OpenAPI for EVE Online
 *
 * OpenAPI spec version: 0.4.1.dev1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

package swagger

// item object
type GetKillmailsKillmailIdKillmailHashItem struct {

	// flag integer
	Flag int32 `json:"flag,omitempty"`

	// item_type_id integer
	ItemTypeId int32 `json:"item_type_id,omitempty"`

	// quantity_destroyed integer
	QuantityDestroyed int64 `json:"quantity_destroyed,omitempty"`

	// quantity_dropped integer
	QuantityDropped int64 `json:"quantity_dropped,omitempty"`

	// singleton integer
	Singleton int32 `json:"singleton,omitempty"`
}
