/* 
 * EVE Swagger Interface
 *
 * An OpenAPI for EVE Online
 *
 * OpenAPI spec version: 0.4.1.dev1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

package swagger

// 200 ok object
type GetCharactersCharacterIdSkillsOk struct {

	// skills array
	Skills []GetCharactersCharacterIdSkillsSkill `json:"skills,omitempty"`

	// total_sp integer
	TotalSp int64 `json:"total_sp,omitempty"`
}
