/* 
 * EVE Swagger Interface
 *
 * An OpenAPI for EVE Online
 *
 * OpenAPI spec version: 0.4.1.dev1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

package swagger

// 200 ok object
type GetIndustrySystems200Ok struct {

	// cost_indices array
	CostIndices []GetIndustrySystemsCostIndice `json:"cost_indices,omitempty"`

	// solar_system_id integer
	SolarSystemId int32 `json:"solar_system_id,omitempty"`
}
