/* 
 * EVE Swagger Interface
 *
 * An OpenAPI for EVE Online
 *
 * OpenAPI spec version: 0.4.1.dev1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

package swagger

// current_vul object
type GetCorporationsCorporationIdStructuresCurrentVul struct {

	// day integer
	Day int32 `json:"day,omitempty"`

	// hour integer
	Hour int32 `json:"hour,omitempty"`
}
