/* 
 * EVE Swagger Interface
 *
 * An OpenAPI for EVE Online
 *
 * OpenAPI spec version: 0.4.1.dev1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

package swagger

// dogma_attribute object
type GetUniverseTypesTypeIdDogmaAttribute struct {

	// attribute_id integer
	AttributeId int32 `json:"attribute_id,omitempty"`

	// value number
	Value float32 `json:"value,omitempty"`
}
