/* 
 * EVE Swagger Interface
 *
 * An OpenAPI for EVE Online
 *
 * OpenAPI spec version: 0.4.1.dev1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

package swagger

// link object
type GetCharactersCharacterIdPlanetsPlanetIdLink struct {

	// destination_pin_id integer
	DestinationPinId int64 `json:"destination_pin_id,omitempty"`

	// link_level integer
	LinkLevel int32 `json:"link_level,omitempty"`

	// source_pin_id integer
	SourcePinId int64 `json:"source_pin_id,omitempty"`
}
