/* 
 * EVE Swagger Interface
 *
 * An OpenAPI for EVE Online
 *
 * OpenAPI spec version: 0.4.1.dev1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

package swagger

// 200 ok object
type GetUniverseStructuresStructureIdOk struct {

	// The full name of the structure
	Name string `json:"name,omitempty"`

	Position GetUniverseStructuresStructureIdPosition `json:"position,omitempty"`

	// solar_system_id integer
	SolarSystemId int32 `json:"solar_system_id,omitempty"`

	// type_id integer
	TypeId int32 `json:"type_id,omitempty"`
}
