/* 
 * EVE Swagger Interface
 *
 * An OpenAPI for EVE Online
 *
 * OpenAPI spec version: 0.4.1.dev1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

package swagger

// required_item object
type GetLoyaltyStoresCorporationIdOffersRequiredItem struct {

	// quantity integer
	Quantity int32 `json:"quantity,omitempty"`

	// type_id integer
	TypeId int32 `json:"type_id,omitempty"`
}
