/* 
 * EVE Swagger Interface
 *
 * An OpenAPI for EVE Online
 *
 * OpenAPI spec version: 0.4.1.dev1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

package swagger

// squad object
type GetFleetsFleetIdWingsSquad struct {

	// id integer
	Id int64 `json:"id,omitempty"`

	// name string
	Name string `json:"name,omitempty"`
}
