/* 
 * EVE Swagger Interface
 *
 * An OpenAPI for EVE Online
 *
 * OpenAPI spec version: 0.4.1.dev1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

package swagger

// 201 created object
type PostFleetsFleetIdWingsWingIdSquadsCreated struct {

	// The squad_id of the newly created squad
	SquadId int64 `json:"squad_id,omitempty"`
}
