/* 
 * EVE Swagger Interface
 *
 * An OpenAPI for EVE Online
 *
 * OpenAPI spec version: 0.4.1.dev1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

package swagger

// label object
type PostCharactersCharacterIdMailLabelsLabel struct {

	// Hexadecimal string representing label color, in RGB format 
	Color string `json:"color,omitempty"`

	// name string
	Name string `json:"name,omitempty"`
}
