/* 
 * EVE Swagger Interface
 *
 * An OpenAPI for EVE Online
 *
 * OpenAPI spec version: 0.4.1.dev1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

package swagger

// 200 ok object
type PostUniverseNames200Ok struct {

	// category string
	Category string `json:"category,omitempty"`

	// id integer
	Id int32 `json:"id,omitempty"`

	// name string
	Name string `json:"name,omitempty"`
}
