/* 
 * EVE Swagger Interface
 *
 * An OpenAPI for EVE Online
 *
 * OpenAPI spec version: 0.4.1.dev1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

package swagger

// recipient object
type PostCharactersCharacterIdMailRecipient struct {

	// recipient_id integer
	RecipientId int32 `json:"recipient_id,omitempty"`

	// recipient_type string
	RecipientType string `json:"recipient_type,omitempty"`
}
