/* 
 * EVE Swagger Interface
 *
 * An OpenAPI for EVE Online
 *
 * OpenAPI spec version: 0.4.1.dev1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

package swagger

// 201 created object
type PostCharactersCharacterIdFittingsCreated struct {

	// fitting_id integer
	FittingId int32 `json:"fitting_id,omitempty"`
}
