/* 
 * EVE Swagger Interface
 *
 * An OpenAPI for EVE Online
 *
 * OpenAPI spec version: 0.4.1.dev1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

package swagger

// 201 created object
type PostCharactersCharacterIdCspaCreated struct {

	// cost integer
	Cost int64 `json:"cost,omitempty"`
}
