/* 
 * EVE Swagger Interface
 *
 * An OpenAPI for EVE Online
 *
 * OpenAPI spec version: 0.4.1.dev1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

package swagger

// new_schedule object
type PutCorporationsCorporationIdStructuresStructureIdNewSchedule struct {

	// Day of the week, zero-indexed to Monday
	Day int32 `json:"day,omitempty"`

	// Hour of the day evetime, zero-indexed to midnight
	Hour int32 `json:"hour,omitempty"`
}
