/* 
 * EVE Swagger Interface
 *
 * An OpenAPI for EVE Online
 *
 * OpenAPI spec version: 0.4.1.dev1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

package swagger

// new_settings object
type PutFleetsFleetIdNewSettings struct {

	// Should free-move be enabled in the fleet
	IsFreeMove bool `json:"is_free_move,omitempty"`

	// New fleet MOTD in CCP flavoured HTML
	Motd string `json:"motd,omitempty"`
}
