/* 
 * EVE Swagger Interface
 *
 * An OpenAPI for EVE Online
 *
 * OpenAPI spec version: 0.4.1.dev1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

package swagger

// response schema
type PutCharactersCharacterIdCalendarEventIdResponse struct {

	// response string
	Response string `json:"response,omitempty"`
}
